#!/usr/bin/env python3
"""Export the 4-quadrant edge coil geometry to RS-274X Gerbers for fab.

Consumes coil_gen.py and writes, into coil/gerber/:
  djembe-coil-F_Cu.gbr        front copper: 4 quadrant serpentine coils + lead pads
  djembe-coil-Edge_Cuts.gbr   annular board outline (outer + inner cut)
  README.txt                  stackup + order notes

This is the TRACE GEOMETRY (the hard part). The 4-layer via stitching that
quadruples turns / parallels for the impedance target, and the connector
breakout, are the next refinement -- the serpentine copper that makes the
Lorentz force is what's emitted here. Coordinates are shifted positive.
"""
import os
import sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import coil_gen as cg

OUTDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gerber")


def _board_radii(p):
    r1 = max(b[2] for b in cg._bands(p)) + 4.0     # outer board radius
    r0 = min(b[1] for b in cg._bands(p)) - 4.0     # inner cutout radius
    return r0, r1


def _writer(off):
    def i(v):
        return str(int(round((v + off) * 1e6)))     # mm -> X46 int, shifted +ve

    def xy(pt):
        return f"X{i(pt[0])}Y{i(pt[1])}"
    return xy


def write_copper(coils, p, off, path):
    xy = _writer(off)
    L = ["G04 digital-djembe 4-quadrant edge coil - F_Cu*",
         "%FSLAX46Y46*%", "%MOMM*%", "%LPD*%",
         f"%ADD10C,{p.trace_w:.4f}*%",               # trace aperture
         "%ADD11C,1.6000*%",                          # lead-pad aperture
         "G01*", "D10*"]
    for coil in coils:                               # one continuous stroked path
        pts = [pt for seg in coil.serpentine() for pt in seg]
        L.append(f"{xy(pts[0])}D02*")
        L += [f"{xy(q)}D01*" for q in pts[1:]]
    L.append("D11*")                                 # two lead pads per coil
    for coil in coils:
        serp = coil.serpentine()
        for term in (serp[0][0], serp[-1][-1]):
            L.append(f"{xy(term)}D03*")
    L.append("M02*")
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")


def write_outline(p, off, path):
    xy = _writer(off)
    r0, r1 = _board_radii(p)
    L = ["G04 digital-djembe coil - Edge_Cuts*",
         "%FSLAX46Y46*%", "%MOMM*%", "%LPD*%",
         "%ADD10C,0.1000*%", "G01*", "D10*"]
    for r in (r1, r0):
        th = np.linspace(0, 2 * np.pi, 361)
        ring = np.c_[r * np.cos(th), r * np.sin(th)]
        L.append(f"{xy(ring[0])}D02*")
        L += [f"{xy(q)}D01*" for q in ring[1:]]
    L.append("M02*")
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")


def write_readme(p, coils, path):
    r0, r1 = _board_radii(p)
    e = coils[0].electrical()
    txt = f"""digital-djembe — planar-magnetic head driver, flex PCB (rev A)
================================================================
Geometry: 4 azimuthal QUADRANT coils on a single EDGE ring of a
{p.head_d:.0f} mm ({p.head_d/25.4:.0f}") drum head. Generated by coil/coil_gen.py.

Board (this Gerber set):
  - Annular flex: outer dia {2*r1:.0f} mm, inner cut dia {2*r0:.0f} mm.
  - Or fab as 4 separate 90-degree wedge tiles (cheaper / easier to handle /
    bond; one botched glue-up replaces one tile). Recommended for rev A.
  - Material: polyimide flex, 4 layer, 2 oz copper.
  - Trace {p.trace_w} mm, bar pitch {p.bar_pitch} mm (serpentine over the gaps).

Per quadrant coil (from coil/bl_sim.py, N42 + steel back-iron):
  - turns {e['turns']}, conductor {e['len_field_m']:.2f} m/layer
  - R {e['R_series']:.1f} ohm (4-layer series) / {e['R_2s2p']:.1f} ohm (2s2p)
  - BL ~0.65 N/A  -> sustain (0.04 N) needs ~60 mA / ~18 mW. Fine.
  - 4 coils -> 4 amp channels (one 4-channel class-D board).

Magnets (SEPARATE fixed plate, NOT on the head — see brackets.scad, TBD):
  - Alternating-polarity bar ring under the coil edge ring.
  - Order against: N52 + 1.5-2 mm gap + steel-shell back-iron (gap is the
    dominant BL lever; see PLAN.md s6.4.2).

STILL TO ADD before ordering:
  - 4-layer via stitching (series for turns / parallel for impedance) + the
    layer pads. This rev is the single-layer trace geometry only.
  - Connector breakout from each coil's two lead pads to a board edge.
  - Confirm the REAL head diameter (open question #1) and re-run coil_gen.

Layers in this set:
  djembe-coil-F_Cu.gbr        front copper (4 coils + 8 lead pads)
  djembe-coil-Edge_Cuts.gbr   board outline
"""
    with open(path, "w") as f:
        f.write(txt)


def main():
    p = cg.Params()
    coils = cg.build_coils(p)
    os.makedirs(OUTDIR, exist_ok=True)
    _, r1 = _board_radii(p)
    off = r1 + 5.0                                   # shift so all coords > 0
    write_copper(coils, p, off, os.path.join(OUTDIR, "djembe-coil-F_Cu.gbr"))
    write_outline(p, off, os.path.join(OUTDIR, "djembe-coil-Edge_Cuts.gbr"))
    write_readme(p, coils, os.path.join(OUTDIR, "README.txt"))
    n_pts = sum(len(s) for c in coils for s in c.serpentine())
    print(f"wrote {OUTDIR}/  ({len(coils)} coils, {n_pts} trace vertices, "
          f"board OD {2*r1:.0f} mm)")
    for f in sorted(os.listdir(OUTDIR)):
        print(f"  {f}")


if __name__ == "__main__":
    main()
